apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
#      livenessprobe:
#        httpGet:
#          path: /healthy
#          port: 3900
#          initialDelaySeconds: 5
#          timeoutSeconds: 1
#          periodSeconds: 10
#          failureThreshold: 3


